version: "1.0"
metadata:
  name: "models"
  description: "Model configurations for different use cases"

models:
  mcp_evaluator_v1:
    name: "MCP Evaluator (Haiku)"
    version: "1.0"
    provider: "anthropic"
    model_id: "claude-3-haiku-20240307"
    config:
      temperature: 0
      max_tokens: 500
    content_limits:
      max_words: 5000
      max_chars: 30000
    cost_per_token:
      input: 0.00025
      output: 0.00125
  
  mcp_evaluator_sonnet:
    name: "MCP Evaluator (Sonnet)"
    version: "1.0"
    provider: "anthropic"
    model_id: "claude-3-5-sonnet-20241022"
    config:
      temperature: 0
      max_tokens: 500
    content_limits:
      max_words: 8000
      max_chars: 50000
    cost_per_token:
      input: 0.003
      output: 0.015